# Generated by Django 4.2.1 on 2023-06-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("middle_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="GeoidLicence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licence", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Licences",
            },
        ),
        migrations.CreateModel(
            name="GeoidMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Methods",
            },
        ),
        migrations.CreateModel(
            name="GeoidStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Status",
            },
        ),
        migrations.CreateModel(
            name="GeoidType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Typologies",
            },
        ),
        migrations.CreateModel(
            name="ModelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Model Groups",
            },
        ),
        migrations.CreateModel(
            name="ModelReferenceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Model Reference Relations",
            },
        ),
        migrations.CreateModel(
            name="ModelSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Model Series",
            },
        ),
        migrations.CreateModel(
            name="Responsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("middle_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Responsibles",
            },
        ),
        migrations.CreateModel(
            name="ModelReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("citation", models.CharField(max_length=200)),
                ("doi", models.CharField(max_length=200)),
                ("attachment_path", models.CharField(max_length=200)),
                ("presentation_path", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                (
                    "refRelation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geoids.modelreferencerelation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Model References",
            },
        ),
        migrations.CreateModel(
            name="Geoid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("description", models.TextField()),
                ("comments", models.TextField()),
                ("crs", models.IntegerField()),
                ("continent", models.CharField(max_length=200)),
                ("zone", models.CharField(max_length=200)),
                ("lat_min", models.FloatField()),
                ("lat_max", models.FloatField()),
                ("lon_min", models.FloatField()),
                ("lon_max", models.FloatField()),
                ("delta_lat", models.FloatField()),
                ("delta_lon", models.FloatField()),
                ("bbox", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("wos", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=200)),
                ("file_path_isg", models.CharField(max_length=200)),
                ("file_path_converted", models.CharField(max_length=200)),
                ("file_extension", models.CharField(max_length=200)),
                ("image_path", models.CharField(max_length=200)),
                ("wms_endpoint", models.CharField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geoids.author"
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geoids.geoidlicence",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geoids.geoidmethod",
                    ),
                ),
                (
                    "modelGroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geoids.modelgroup",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geoids.responsible",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geoids.geoidstatus",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geoids.geoidtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Model",
            },
        ),
    ]
